apiVersion: v2
name: common
description: A library chart for microservice based applications
type: library
version: 1.3.0
appVersion: "1.0.0"

maintainers:
  - email: name-istakenn@gmail.com
    name: OC # Otieno Calvine
    url: https://calvineotieno.com
