# Default values for services/apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # -- (int) Numbers of replicas
  replicaCount: 1
  environment: {}
  minReplicas: 1
  maxReplicas: 4
  targetCPUup: 75

image:
  # -- The docker image tag to use
  # -- @default Chart version
  tag: latest
  # -- The docker image repository to use
  name: twalter/openshift-nginx
build:
  enabled: false
deploy:
  enabled: true
  replicas: 1
  servicePort: 8081
  containerPort: 8081
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    # httpGet:
    #   path: /health/live
    #   port: admin
  
  # -- Freeform readinessProbe field.
  # @default HTTP Get on <ip>:admin/health/live
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
# -- Freeform resources items
  resources: {}

### Service specific environment variables
environment: {}

### Service specific secrets
secrets: {}
