global:
  replicaCount: 1
  environment: {}
  minReplicas: 1
  maxReplicas: 4
  targetCPUup: 75

image:
  tag: latest
  name: twalter/openshift-nginx
build:
  enabled: false
deploy:
  enabled: true
  replicas: 1
  servicePort: 8081
  containerPort: 8081
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    # httpGet:
    #   path: /health/live
    #   port: admin
  readinessProbe:
    # httpGet:
    #   path: /health/ready
    #   port: admin

  resources:
    limits:
      cpu: 200m
      memory: 400M
    requests:
      cpu: 100m
      memory: 200M

### Service specific environment variables
environment: {}

### Service specific secrets
secrets: {}
