repos:
  - repo: https://github.com/NYARAS/ocp-umbrella-helm-chart
    # rev: v0.10.0
    hooks:
      - id: helm-docs
        args:
          - --template-files=README.md.gotmpl
          - --badge-style=for-the-badge
