stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"
- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
    pool:
      vmImage: ubuntu-latest
    environment: 'dev-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
- stage: qa_deploy
  jobs:
  - deployment: qa_deploy
    pool:
      vmImage: ubuntu-latest
    environment: 'qa-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, qa world !!!"

trigger:
- feature/configure-azure-pipeline

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
