{{- define "common.hpa.tpl" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.appName" . }}
  labels: {}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.appName" . }}
  minReplicas: {{ .Values.global.minReplicas }}
  maxReplicas: {{ .Values.global.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.global.targetCPUup }}
{{- end -}}
{{- end -}}

{{- define "common.hpa" -}}
{{- include "common.util.merge" (append . "common.hpa.tpl") -}}
{{- end -}}
