{{- define "common.secret.tpl" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.appName" . }}
  labels: {}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}

{{- end -}}
{{- end -}}

{{- define "common.secret" -}}
{{- include "common.util.merge" (append . "common.secret.tpl") -}}
{{- end -}}
