{{- define "common.secret.tpl" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.appName" . }}
  labels: {}
type: Opaque
data:
  amq.username: {{ .Values.amq.secret.data.username }}
  amq.password: {{ .Values.amq.secret.data.password }}

{{- end -}}
{{- end -}}

{{- define "common.secret" -}}
{{- include "common.util.merge" (append . "common.secret.tpl") -}}
{{- end -}}
