# Default values for services/apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  replicaCount: 1
  environment: {}
  minReplicas: 1
  maxReplicas: 4
  targetCPUup: 75

image:

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

environment: {}


amq:
  username: ""
  password: ""
